### ISSUE TITLE
Configure how often to perform lr_scheduler.step()

### ISSUE THREAD

**Issue by fotstrt** [eth-easl/modyn#163]
Currently, if a `lr_scheduler` is provided, we call `lr_scheduler.step()` at each training step. However, the user might need to update the `lr_scheduler` at a different granularity, for example [per epoch](https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate). This should be configurable, for example via the pipeline config file.

**Comment by MaxiBoether** [comment]
Closed :)
