### ISSUE TITLE
Accelerate online dataset prefetching if needed

### ISSUE THREAD

**Issue by fotstrt** [eth-easl/modyn#175]
Currently, prefetching the next partition of keys and samples is done synchronously by each data worker. It is not clear yet if this will block/delay training or not. If it turns out to do so, we would probably need some kind of multithreading or `asyncio` support.

**Comment by MaxiBoether** [comment]
This also affects the EvaluationDataset introdocued in #269

**Comment by MaxiBoether** [comment]
Solved (for now) by #301.
