### ISSUE TITLE
Connect Evaluator

### ISSUE THREAD

**Issue by robin-oester** [eth-easl/modyn#280]
After #269 is merged, we want to connect the evaluator to the system. In particular we want to:
- let supervisor interact with evaluator via gRPC calls
- evaluate models after each trigger on configured (static) dataset
- store evaluation results persistently
- test pipeline end-to-end
- (format used to store results should be readable for a visualization tool like TensorBoard)

**Comment by MaxiBoether** [comment]
Closed by #287.
