### ISSUE TITLE
Make the supervisor a server and create a separate modyn_client

### ISSUE THREAD

**Issue by jenny011** [eth-easl/modyn#317]
Currently, we instantiate a supervisor per pipeline.\
We want to make an architectural change to the supervisor:
1. Make the supervisor a grpc server that registers, executes and monitors pipelines upon StartPipeline requests from the client. First, we need to finish #302. 
2. Create a separate modyn_client that can submit pipelines to the supervisor and receive execution results.

**Comment by MaxiBoether** [comment]
An open question we have to resolve is how to do the visualization. Currently, we use enlighten at the legacy supervisor. To achieve the same result with the Modyn CLI and Supervsior server, we would need to send status progress messages frequently to the CLI client (via gRPC), and use enlighten on the CLI. Maybe there also is an alternative

**Comment by robinholzi** [comment]
Seems to be implemented, feel free to reopen if needed
