### ISSUE TITLE
Validate modyn_config

### ISSUE THREAD

**Issue by jenny011** [eth-easl/modyn#325]
There is currently no validation on modyn_config.
Add validation similar to validate_pipeline_config().

**Comment by vGsteiger** [comment]
Hi @jenny011, there is something similar [here](https://github.com/eth-easl/modyn/blob/17cd2640a51d4a393ef910828ab2b1c95f1bd911/modyn/storage/storage.py#L44C2-L44C2), maybe extract that to the utils.

**Comment by robinholzi** [comment]
Done with https://github.com/eth-easl/modyn/pull/423, https://github.com/eth-easl/modyn/pull/435
