### ISSUE TITLE
Trainer_server: inaccurate measurement of operations on GPU

### ISSUE THREAD

**Issue by XianzheMa** [eth-easl/modyn#396]
The current way to measure operations on GPU, e.g. forward pass, backward pass, etc. is not accurate ([here](https://github.com/eth-easl/modyn/blob/ed861c92cc05f7ab99b2694df4f1281234539639/modyn/trainer_server/internal/trainer/pytorch_trainer.py#L410) as an example), because CUDA kernels are executed asynchronously. Instead of
```python
stopw.start("Forward", resume=True)
output = self._model.model(data)
stopw.stop("Forward")
```

we should synchronize cuda operations, i.e. do

```python
torch.cuda.synchronize(device=self._device)
stopw.start("Forward", resume=True)
output = self._model.model(data)
torch.cuda.synchronize(device=self._device)
stopw.stop("Forward")
```
.

Here is a chart to manifest the difference:
![image](https://github.com/eth-easl/modyn/assets/100585941/b1a67c59-dc1a-44ce-b039-5e1c866b6585)

 The left panel is without cuda synchronization and the right is with.

**Comment by XianzheMa** [comment]
However, we probably don't want to directly inject those synchronization lines into the program, as synchronization slows down the training process. We should have a config "measure_gpu_operations", when set to True, we use the stop watch and add cuda synchronization.

**Comment by robinholzi** [comment]
> However, we probably don't want to directly inject those synchronization lines into the program, as synchronization slows down the training process. We should have a config "measure_gpu_operations", when set to True, we use the stop watch and add cuda synchronization.

For my use case where I want to have a more fine granular view on the "Training" pipeline stage a synchronization option `measure_gpu_operations` wouldn't be a fair experiment setup. This is because I don't only want to compare the operations within training, but also set them into relation with other costs like trigger policy evaluation or information the selector. CUDA synchronization would probably affect training time negatively, skewing the comparison on pipeline level.

**Comment by robinholzi** [comment]
Adding synchronization everywhere also looks quite brittle as we have quite some model calls spread across several loops and functions. It's quite easy to miss sth. there.

**Comment by MaxiBoether** [comment]
No, for sure we don't want synchronization because that will decrease throughput. We cannot really measure those individual ops, unfortunately, just overall time spent training.

**Comment by XianzheMa** [comment]
> > However, we probably don't want to directly inject those synchronization lines into the program, as synchronization slows down the training process. We should have a config "measure_gpu_operations", when set to True, we use the stop watch and add cuda synchronization.
> 
> For my use case where I want to have a more fine granular view on the "Training" pipeline stage a synchronization option `measure_gpu_operations` wouldn't be a fair experiment setup. This is because I don't only want to compare the operations within training, but also set them into relation with other costs like trigger policy evaluation or information the selector. CUDA synchronization would probably affect training time negatively, skewing the comparison on pipeline level.

sorry to miss this comment. Good perspective. but I think we can
1. enable `measure_gpu_operations` to compare steps inside training.
2. disable `measure_gpu_operations` to compare pipeline level stages.
